-- rasse
--
-- Generiert aus content/import/rasse.csv per csv_to_seed_sql.py -- siehe dort
-- (README) fuer Herkunft und Einschraenkungen der Daten. `on conflict do
-- nothing`: erneutes Ausfuehren (z. B. nach `supabase db reset`)
-- dupliziert nichts.

insert into rasse (id, name, rassegruppe) values
  ('deutscher_schaeferhund', 'Deutscher Schäferhund', 'huete'),
  ('border_collie', 'Border Collie', 'huete'),
  ('australian_shepherd', 'Australian Shepherd', 'huete'),
  ('australian_cattle_dog', 'Australian Cattle Dog', 'huete'),
  ('welsh_corgi_pembroke', 'Welsh Corgi Pembroke', 'huete'),
  ('beauceron', 'Beauceron', 'huete'),
  ('shetland_sheepdog', 'Shetland Sheepdog (Sheltie)', 'huete'),
  ('bearded_collie', 'Bearded Collie', 'huete'),
  ('puli', 'Puli', 'huete'),
  ('altdeutscher_huetehund', 'Altdeutscher Hütehund', 'huete'),
  ('dobermann', 'Dobermann', 'molosser'),
  ('rottweiler', 'Rottweiler', 'molosser'),
  ('boxer', 'Boxer', 'molosser'),
  ('deutsche_dogge', 'Deutsche Dogge', 'molosser'),
  ('berner_sennenhund', 'Berner Sennenhund', 'molosser'),
  ('bernhardiner', 'Bernhardiner', 'molosser'),
  ('cane_corso', 'Cane Corso', 'molosser'),
  ('neapolitanischer_mastino', 'Neapolitanischer Mastino', 'molosser'),
  ('riesenschnauzer', 'Riesenschnauzer', 'molosser'),
  ('zwergschnauzer', 'Zwergschnauzer', 'molosser'),
  ('mastiff', 'Mastiff', 'molosser'),
  ('boston_terrier', 'Boston Terrier', 'begleit'),
  ('kangal', 'Kangal', 'herdenschutz'),
  ('pyrenaeenberghund', 'Pyrenäenberghund', 'herdenschutz'),
  ('maremmano_abruzzese', 'Maremmano-Abruzzese Schäferhund', 'herdenschutz'),
  ('kuvasz', 'Kuvasz', 'herdenschutz'),
  ('kaukasischer_owtscharka', 'Kaukasischer Owtscharka', 'herdenschutz'),
  ('tibet_dogge', 'Tibet-Dogge', 'herdenschutz'),
  ('jack_russell_terrier', 'Jack Russell Terrier', 'terrier'),
  ('foxterrier', 'Foxterrier', 'terrier'),
  ('bullterrier', 'Bullterrier', 'terrier'),
  ('staffordshire_bullterrier', 'Staffordshire Bullterrier', 'terrier'),
  ('american_staffordshire_terrier', 'American Staffordshire Terrier', 'terrier'),
  ('west_highland_white_terrier', 'West Highland White Terrier', 'terrier'),
  ('yorkshire_terrier', 'Yorkshire Terrier', 'terrier'),
  ('airedale_terrier', 'Airedale Terrier', 'terrier'),
  ('cairn_terrier', 'Cairn Terrier', 'terrier'),
  ('scottish_terrier', 'Scottish Terrier', 'terrier'),
  ('dackel', 'Dackel', 'jagd'),
  ('beagle', 'Beagle', 'jagd'),
  ('deutsche_bracke', 'Deutsche Bracke', 'jagd'),
  ('basset_hound', 'Basset Hound', 'jagd'),
  ('bracke_st_hubert', 'Bracke St. Hubert (Bloodhound)', 'jagd'),
  ('rhodesian_ridgeback', 'Rhodesian Ridgeback', 'jagd'),
  ('deutsch_kurzhaar', 'Deutsch Kurzhaar', 'jagd'),
  ('deutsch_drahthaar', 'Deutsch Drahthaar', 'jagd'),
  ('weimaraner', 'Weimaraner', 'jagd'),
  ('pointer', 'Pointer', 'jagd'),
  ('irish_setter', 'Irish Setter', 'jagd'),
  ('englisch_setter', 'Englisch Setter', 'jagd'),
  ('labrador_retriever', 'Labrador Retriever', 'jagd'),
  ('golden_retriever', 'Golden Retriever', 'jagd'),
  ('cocker_spaniel', 'Cocker Spaniel', 'jagd'),
  ('englischer_springer_spaniel', 'Englischer Springer Spaniel', 'jagd'),
  ('magyar_vizsla', 'Magyar Vizsla', 'jagd'),
  ('siberian_husky', 'Siberian Husky', 'nordisch'),
  ('alaskan_malamute', 'Alaskan Malamute', 'nordisch'),
  ('akita', 'Akita', 'nordisch'),
  ('chow_chow', 'Chow-Chow', 'nordisch'),
  ('deutscher_spitz', 'Deutscher Spitz', 'nordisch'),
  ('samojede', 'Samojede', 'nordisch'),
  ('shiba_inu', 'Shiba Inu', 'nordisch'),
  ('finnischer_lapphund', 'Finnischer Lapphund', 'nordisch'),
  ('chihuahua', 'Chihuahua', 'begleit'),
  ('mops', 'Mops', 'begleit'),
  ('malteser', 'Malteser', 'begleit'),
  ('cavalier_king_charles_spaniel', 'Cavalier King Charles Spaniel', 'begleit'),
  ('havaneser', 'Havaneser', 'begleit'),
  ('pudel', 'Pudel', 'begleit'),
  ('bichon_frise', 'Bichon Frisé', 'begleit'),
  ('shih_tzu', 'Shih Tzu', 'begleit'),
  ('franzoesische_bulldogge', 'Französische Bulldogge', 'begleit'),
  ('lhasa_apso', 'Lhasa Apso', 'begleit'),
  ('zwergpinscher', 'Zwergpinscher', 'begleit'),
  ('englische_bulldogge', 'Englische Bulldogge', 'begleit'),
  ('greyhound', 'Greyhound', 'wind'),
  ('whippet', 'Whippet', 'wind'),
  ('afghanischer_windhund', 'Afghanischer Windhund', 'wind'),
  ('barsoi', 'Barsoi', 'wind'),
  ('irish_wolfhound', 'Irish Wolfhound', 'wind'),
  ('saluki', 'Saluki', 'wind'),
  ('galgo_espanol', 'Galgo Español', 'wind')
on conflict (id) do nothing;
